---
language: csharp

git:
  depth: 1

stages:
  - warm up dependencies
  # - sanity testing
  - build
  # - acceptance testing

jobs:
  include:
    - stage: warm up dependencies
      mono: latest
      dotnet: 2.1
      script:
        - nuget update -self
        - nuget install -OutputDirectory deps NETStandard.Library.NETFramework
        - nuget install -OutputDirectory deps Newtonsoft.Json
        - nuget install -OutputDirectory deps PowerShellStandard.Library
    - stage: build
      script:
        - make sdk

matrix:
  fast_finish: true
  allow_failures:
  - stage: sanity testing
  - script: make sanity
  # include:
  #   - dotnet: 2.1
  #     mono: none
  #     env: DOTNETCORE=1
  #   - mono: latest