---
language: csharp

git:
  depth: 1

mono: none
dotnet: 2.1

stages:
  - warm up dependencies
  # - sanity testing
  - build
  # - acceptance testing

jobs:
  include:
    - stage: warm up dependencies
      script:
        - nuget update -self
        - make deps
    - stage: build
      script:
        - make sdk

matrix:
  fast_finish: true
  allow_failures:
  - stage: sanity testing
  - script: make sanity