---
language: generic

git:
  depth: 1

os: linux
dist: xenial
dotnet: 2.1

install:
  - wget -q https://packages.microsoft.com/config/ubuntu/16.04/packages-microsoft-prod.deb
  - sudo dpkg -i packages-microsoft-prod.deb
  - sudo apt-get update
  - sudo apt-get install -y powershell

script:
  - pwsh -File build-module.ps1"

matrix:
  fast_finish: true

# travis-ci will quit using the cache if an enviroment variable changes.
# CACHE_VERSION is not used for anything other than invalidating the cache.
# DOTNET_SKIP_FIRST_TIME_EXPERIENCE is to skip the dotnet-cli initialization,
# which is expensive and unneeded for build agents.
env:
  global:
    - CACHE_VERSION=netcoreapp.2.1-sdk.2.1.300
    - POWERSHELL_TELEMETRY_OPTOUT=1
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1

cache:
  timeout: 360
  directories:
    - $HOME/.nuget
    - deps
