version: 0.1

jobs:
  build:
    machine:
      enabled: true
    working_directory: ~/project/Powershell
    steps:
      - run:
          command: git clone http://github.com/nutanix/Powershell
      - run:
          command: sudo rpm -Uvh https://packages.microsoft.com/config/rhel/7/packages-microsoft-prod.rpm
      - run:
          command: sudo yum update
      - run:
          command: sudo yum -y install dotnet-sdk-2.1
      - run:
          command: dotnet build
